devices([
  "iPad Air",
  "iPad Pro (12.9 inch)",
  "iPhone 4s",
  "iPhone 5",
  "iPhone 6",
  "iPhone 6 Plus"
])

languages([
  "en-US",
  "fr",
  "da",
])

scheme "AntidoteScreenshots"
reinstall_app true
clear_previous_screenshots true
number_of_retries 4
stop_after_first_error true
