# devices([
#   "iPhone 6",
#   "iPhone 6 Plus",
#   "iPhone 5",
#   "iPad Pro (12.9 inch)",
#   "iPad Pro (9.7 inch)"
# ])

languages([
  "en",
  "de",
  "ru",
#   "it-IT",
#   ["pt", "pt_BR"] # Portuguese with Brazilian locale
])

scheme "AntidoteScreenshots"
reinstall_app true
clear_previous_screenshots true
number_of_retries 4
stop_after_first_error true
