devices([
  "iPad Air",
  "iPad Pro",
  "iPhone 4s",
  "iPhone 5",
  "iPhone 6",
  "iPhone 6 Plus"
])

languages([
  "en-US",
#  "de",
#  "ru",
#   "it-IT",
#   ["pt", "pt_BR"] # Portuguese with Brazilian locale
])

scheme "AntidoteScreenshots"
reinstall_app true
clear_previous_screenshots true
number_of_retries 4
stop_after_first_error true
